name = "unbelong-img-cdn"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 データベース
[[d1_databases]]
binding = "DB"
database_name = "unbelong-db"
database_id = "60316b26-074e-4fd3-a06b-272bc198b6b1"

[vars]
CLOUDFLARE_ACCOUNT_HASH = "xxx" # Cloudflare Images のアカウントハッシュ
