name = "tokyo86-img-cdn"
main = "src/index.ts"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "img.tokyo86.com", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "tokyo86-db"
database_id = "0614fe1a-8e77-4c8b-9a87-33584de86905"

[vars]
CLOUDFLARE_ACCOUNT_HASH = "wdR9enbrkaPsEgUtgFORrw"
