name = "tokyo86-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 データベース
[[d1_databases]]
binding = "DB"
database_name = "tokyo86-db"
database_id = "0614fe1a-8e77-4c8b-9a87-33584de86905"

# 環境変数
[vars]
ALLOWED_ORIGINS = "*"
CLOUDFLARE_ACCOUNT_ID = "c677241d7d66ff80103bab9f142128ab"

[env.production.vars]
ALLOWED_ORIGINS = "https://tokyo86-admin.pages.dev,https://unbelong-hono-admin.pages.dev,https://admin.unbelong.xyz,https://comic.unbelong.xyz,https://illust.unbelong.xyz,https://tokyo86.com,https://www.tokyo86.com,https://illust.tokyo86.com"
CLOUDFLARE_ACCOUNT_ID = "c677241d7d66ff80103bab9f142128ab"

[[env.production.d1_databases]]
binding = "DB"
database_name = "tokyo86-db"
database_id = "0614fe1a-8e77-4c8b-9a87-33584de86905"
